services:
  distributor:
    build:
      context: ./Distributor
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/public"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./Distributor:/app
    restart: unless-stopped
    networks:
      - scrape_network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://distributor:8080
      - AUTH_TOKEN=${AUTH_TOKEN}
      - NEXT_PUBLIC_STACK_API_URL=${NEXT_PUBLIC_STACK_API_URL}
      - NEXT_PUBLIC_STACK_PROJECT_ID=${NEXT_PUBLIC_STACK_PROJECT_ID}
      - NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY=${NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY}
      - STACK_SECRET_SERVER_KEY=${STACK_SECRET_SERVER_KEY}
    depends_on:
      distributor:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - scrape_network

  runner:
    build:
      context: ./Runner
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - RUNNER_ID=runner-${HOSTNAME:-runner}
      - DISTRIBUTOR_URL=http://distributor:8080
    depends_on:
      distributor:
        condition: service_healthy
    volumes:
      - ./Runner:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    networks:
      - scrape_network

networks:
  scrape_network:
    driver: bridge
