name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        cache: 'pip'
        cache-dependency-path: |
          requirements.txt
          requirements-dev.txt
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
        pip install --no-cache-dir -r requirements-dev.txt
    
    - name: Create test files
      run: |
        mkdir -p app/static
        echo "test.example.com:user:pass" > app/static/scraper.txt
        echo "127.0.0.1:8080:user:pass" > app/static/proxies.txt
    
    - name: Run tests
      env:
        AUTH_TOKEN: test_token
        WEBSHARE_TOKEN: test_webshare_token
        ENV: test
      run: |
        python -m pytest --cov=app --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
      
    - name: Cleanup
      if: always()
      run: |
        rm -rf .pytest_cache
        rm -rf .coverage
        rm -rf coverage.xml
        rm -rf htmlcov
        rm -rf app/static/*.